---
version: "2"
services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia?Yekaterinburg
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - /etc/qbittorrent/config:/config
      - /mnt/data:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped