---
version: "2"
services:
  qbittorrent:
      image: gists/qbittorrent
      ports:
          - "8080:8080"
          - "6881:6881"
          - "6881:6881/udp"
      volumes:
          - /mnt/data:/data
      environment:
          - UID=1000
          - GID=1000
    restart: always